[project]
name = "pdf-parsing-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litellm>=1.72.6.post2",
    "pillow>=11.2.1",
    "pydantic>=2.11.5",
    "pymupdf>=1.26.0",
    "python-levenshtein>=0.27.1",
    "tenacity>=9.1.2",
]
